# Default Travis java
language: java


before_install:
  -  sudo apt-get update -f
  -  sudo apt-get install -f unzip
before_script:
    - wget http://downloads.sourceforge.net/project/lportal/Liferay%20Portal/7.0.0%20M3/liferay-portal-tomcat-7.0-ce-m3-20141217115214620.zip -O /tmp/liferay.zip
  - unzip -qq /tmp/liferay.zip -d /tmp
  - ln -s /tmp/liferay-portal-7.0-ce-m3 /tmp/liferay-home
  - echo "app.server.parent.dir=/tmp/liferay-home" > "${TRAVIS_BUILD_DIR}/build.${LOGNAME}.properties"


